version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - aws-cli/setup
      - eb/setup
     
      - run:
          name: install Api dependencies
          command: npm run install:api
      - run:
          name: build api
          command: npm run build:api
      - run:
          name: deploy backend
          command: npm run deploy:api
      - run:
          name: install frontEnd dependencies
          command: npm run install:frontend
      - run:
          name: Build frontEnd
          command: npm run build:frontend
      - run:
          name: deploy frontEnd
          command: npm run frontend:deploy

      
workflows:
  udagram:
    jobs:
      - deploy